"""
Anelastic Love Number Algorithm
"""

from .constants import (
    COMPLEX_PARTS,
    DEFAULT_PARAMETER_LINES_FILE_NAME,
    DEFAULT_PARAMETER_LINES_PATH,
    DEFAULT_PERIOD_TAB_PER_DEGREE_FILE_NAME,
    DEFAULT_PERIOD_TAB_PER_DEGREE_PATH,
    DEFAULT_REFERENCE_LOVE_NUMBERS_PATH,
    ELASTIC_PERIOD_TAB,
    PARTIAL_PERIOD_TAB,
    ROOT_PATH,
    SECONDS_PER_YEAR,
    SOLID_EARTH_NUMERICAL_MODEL_PART_NAMES_SEPARATOR,
    SOLID_EARTH_NUMERICAL_MODELS_PATH,
    TEST_ELASTIC_INTEGRATION_PATH,
    TEST_PARAMETERS_FILE_PATH,
    TEST_PARAMETERS_SAVE_PATH,
    TEST_SOLID_EARTH_MODEL_PROFILE_DESCRIPTIONS_PATH,
    TEST_SOLID_EARTH_NUMERICAL_MODEL_PATH,
    G,
    generate_degree_tab,
    save_figure,
)
from .integration_loops import (
    DEFAULT_FOR_GINS_OUTPUT_DIRECTORY,
    NUMERICAL_TOLERANCE,
    initialize_test,
    load_reference_love_numbers_for_validation,
    partials_per_parameter_integration_tests,
    verify_solid_earth_numerical_model_consistency,
    viscous_model_integration_test,
)
from .load_solid_earth_model import load_solid_earth_numerical_model
from .love_numbers_for_gins import (
    MODELS,
    compute_love_numbers_for_gins,
    load_love_numbers_for_gins,
    parameters_for_gins,
)
from .parameters import (
    DEFAULT_COMPONENT_PARAMETERS,
    ComponentParameters,
    LoveNumbersLauncher,
    SolidEarthParameters,
    build_base_name,
    generate_parameter_lines,
    launch_love_numbers_computing,
)
from .solid_earth_model import (
    SolidEarthModelDescription,
    SolidEarthNumericalModel,
    compose_name_with_invertible_parameters,
    format_name_function,
)

to_import = [
    COMPLEX_PARTS,
    DEFAULT_PARAMETER_LINES_FILE_NAME,
    DEFAULT_PARAMETER_LINES_PATH,
    DEFAULT_PERIOD_TAB_PER_DEGREE_FILE_NAME,
    DEFAULT_PERIOD_TAB_PER_DEGREE_PATH,
    DEFAULT_REFERENCE_LOVE_NUMBERS_PATH,
    ELASTIC_PERIOD_TAB,
    PARTIAL_PERIOD_TAB,
    ROOT_PATH,
    SECONDS_PER_YEAR,
    SOLID_EARTH_NUMERICAL_MODEL_PART_NAMES_SEPARATOR,
    SOLID_EARTH_NUMERICAL_MODELS_PATH,
    TEST_ELASTIC_INTEGRATION_PATH,
    TEST_PARAMETERS_FILE_PATH,
    TEST_PARAMETERS_SAVE_PATH,
    TEST_SOLID_EARTH_MODEL_PROFILE_DESCRIPTIONS_PATH,
    TEST_SOLID_EARTH_NUMERICAL_MODEL_PATH,
    G,
    generate_degree_tab,
    save_figure,
    DEFAULT_FOR_GINS_OUTPUT_DIRECTORY,
    NUMERICAL_TOLERANCE,
    initialize_test,
    load_reference_love_numbers_for_validation,
    partials_per_parameter_integration_tests,
    verify_solid_earth_numerical_model_consistency,
    viscous_model_integration_test,
    load_solid_earth_numerical_model,
    MODELS,
    compute_love_numbers_for_gins,
    load_love_numbers_for_gins,
    parameters_for_gins,
    DEFAULT_COMPONENT_PARAMETERS,
    ComponentParameters,
    LoveNumbersLauncher,
    SolidEarthParameters,
    build_base_name,
    generate_parameter_lines,
    launch_love_numbers_computing,
    SolidEarthModelDescription,
    SolidEarthNumericalModel,
    compose_name_with_invertible_parameters,
    format_name_function,
]
